language: R
sudo: false
cache: packages
warnings_are_errors: true
r_check_args: "--as-cran"
env:
  global:
    secure: Ev4TZp9HmPzres9QOaCSJJcBcM0+noCp3AtHGsFhFLHbeMCiKn23mPI0umWnceOtBhGApDjnoj+jFY5WGZeZ93848wO73ZYvCEQhdyqD1+UwUnnYZWIqkGdxA5Yvi70cEM3Ut+KdiQ46gD8QhFwiUd7REFKbLi/eN+3lQ4NXQWPa8PMJRAxVv8VyseZql1nlDEmyIwT0b3uIJ2A6WVibxjt5XjEI7zI6lC8TCD7Q0fXj0oFHXeqKyeSMBncHkfujPgqDGRrV0iNEQ3vEhPX9JZYJC5oIn4To21x4u3Tq6E71x8CB0Qvh9dAJLfrt9mQW9E8XtkCNpC+5en94NtlUKlSZMk6iBHMgBPDdOPTiBWq/IZIVcKgtAcGnVVaXUK8qnoXa3xNti69NEvULCTuAJ27ojFUK0gDhO0AdXtdhy9ysa7rppvjlaAh2vhfYB6ojrIVULicSnQCjf5QaGwtrDDlFOVLU3pIOZTIYTGKK0tI2qRuyNbZQjfdt5ivD/AhK3jJKZC5ItEoYO/V4SrBnu/eJdVM6Iu985foslp4UFLN0HSIblGSXO73mIEUQpKMbn94FVxjko3LA6Zp6HDkyPB/20cDR8Ctwm/+qC+Q/qY/aT0RfyS7FdFq1HGeT7SfJjcFO2F5ZaFdH65om5bYp7ySVyDm0eprGQjkTST05rAI=
